---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.7
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: carpenike
      email: carpenike@@users.noreply.github.com
    global:
      persistence:
        storageClass: ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s
    ingress:
      create: true
      class: traefik
      host: "k10.${SECRET_DOMAIN}"
      urlPath: k10
      hosts:
        - "k10.${SECRET_DOMAIN}"
      tls:
        enabled: true
        secretName: "tls.k10"
    grafana:
      enabled: false
