---
common_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
common_fallback_ntp_servers:
  - 0.arch.pool.ntp.org
  - 1.arch.pool.ntp.org
  - 2.arch.pool.ntp.org
