---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: collab
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: forecastle
      version: v1.0.98
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m
  values:
    forecastle:
      config:
        title: "Healthchecks"
        namespaceSelector:
          matchNames:
            - collab
            - home
            - media
            - network
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # traefik.ingress.kubernetes.io/router.middlewares: "network-internal-auth@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: home.${SECRET_DOMAIN}
            paths:
              - /
          - host: services.${SECRET_DOMAIN}
            paths:
              - /
        tls:
          - hosts:
              - home.${SECRET_DOMAIN}
              - services.${SECRET_DOMAIN}
