---
- hosts:
    - masters
    - workers
  become: true
  pre_tasks:
    - name: "Add OS variables"
      include_vars: "../family_vars/{{ ansible_os_family | lower }}.yml"
  roles:
    - cluster
    - cni
    - helm-operator
