---
# session:
#   redis:
#     high_availability:
#       sentinel_name: redis-master
#       nodes:
#         - host: redis-node-0.redis-headless.db.svc.cluster.local
#           port: 26379
#         - host: redis-node-1.redis-headless.db.svc.cluster.local
#           port: 26379
#         - host: redis-node-2.redis-headless.db.svc.cluster.local
#           port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["grafana.${SECRET_DOMAIN}"]
      policy: bypass

    - domain:
        - "lidarr.${SECRET_DOMAIN}"
        - "prowlarr.${SECRET_DOMAIN}"
        - "audio.${SECRET_DOMAIN}"
        - "ebooks.${SECRET_DOMAIN}"
        - "radarr.${SECRET_DOMAIN}"
        - "radarr-uhd.${SECRET_DOMAIN}"
        - "sabnzbd.${SECRET_DOMAIN}"
        - "sonarr.${SECRET_DOMAIN}"
        - "sonarr-uhd.${SECRET_DOMAIN}"
      policy: bypass
      resources: ["^/api([?/].*)?$"]

    # - domain: "*.${SECRET_DOMAIN}"
    #   policy: bypass
    #   networks: ["internal"]

identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${SECRET_AUTHELIA_GRAFANA_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://grafana.${SECRET_DOMAIN}/login/generic_oauth"
        userinfo_signing_algorithm: none

      - id: k10
        description: Kasten K10
        secret: "${SECRET_AUTHELIA_K10_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://k10.${SECRET_DOMAIN}/k10/auth-svc/v0/oidc/redirect"
        userinfo_signing_algorithm: none

      - id: synapse
        description: Matrix Synapse
        secret: "${SECRET_AUTHELIA_MATRIX_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://synapse.${SECRET_DOMAIN}/_synapse/client/oidc/callback"
        userinfo_signing_algorithm: none

      - id: gitea
        description: Gitea
        secret: "${SECRET_AUTHELIA_GITEA_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://git.${SECRET_DOMAIN}/user/oauth2/authelia/callback"
        userinfo_signing_algorithm: none

      - id: mastodon
        description: Mastodon
        secret: "${SECRET_AUTHELIA_MASTODON_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://mastodon.${SECRET_DOMAIN}/auth/auth/openid_connect/callback"
        userinfo_signing_algorithm: none

      - id: weave-gitops
        description: Weave GitOps
        secret: "${SECRET_AUTHELIA_WEAVEGITOPS_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://gitops.${SECRET_DOMAIN}/oauth2/callback"]
        userinfo_signing_algorithm: none

      # - id: miniflux
      #   description: Miniflux
      #   secret: "${SECRET_MINIFLUX_OAUTH_CLIENT_SECRET}"
      #   public: false
      #   authorization_policy: two_factor
      #   pre_configured_consent_duration: 1y
      #   scopes:
      #     - openid
      #     - profile
      #     - groups
      #     - email
      #   redirect_uris:
      #     - "https://miniflux.${INGRESS_DOMAIN}/oauth2/oidc/callback"
      #   userinfo_signing_algorithm: none

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
