---
- name: applying kube-router
  command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/carpenike/k8s-gitops/master/manifests/generic-kuberouter-only-advertise-routes.yaml
    #creates: /etc/cni/net.d/10-calico.conflist

- name: Install Helm v3
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Add Cilium Repo
  command:
    cmd: helm repo add cilium https://helm.cilium.io/

- name: Deploy Cilium
  shell: |
    helm upgrade -i cilium cilium/cilium --version {{ cilium_helm_version }} \
    --set global.registry="docker.io/cilium" \
    --set global.tag="{{ cilium_image_version }}" \
    --set global.tunnel="disabled" \
    --set global.nativeRoutingCIDR="{{ cluster_pod_subnet }}" \
    --set global.externalIPs.enabled="true" \
    --set global.ipam.operator.clusterPoolIPv4PodCIDR="{{ cluster_pod_subnet }}" \
    --set global.ipam.operator.clusterPoolIPv4MaskSize="24" \
    --namespace kube-system

# - name: Deploy Cilium
#   shell: |
#     helm upgrade -i cilium cilium/cilium --version {{ cilium_helm_version }} \
#     --set global.registry="docker.io/cilium" \
#     --set global.tag="{{ cilium_image_version }}" \
#     --set global.tunnel="disabled" \
#     --set global.nativeRoutingCIDR="{{ cluster_pod_subnet }}" \
#     --set global.externalIPs.enabled="true" \
#     --set global.ipam.operator.clusterPoolIPv4PodCIDR="{{ cluster_pod_subnet }}" \
#     --set global.kubeProxyReplacement=strict \
#     --set global.k8sServiceHost=10.20.10.16 \
#     --set global.k8sServicePort=6443 \
#     --namespace kube-system
