---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: security
spec:
  releaseName: dex
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.32.0
    env:
      KUBERNETES_POD_NAMESPACE: security
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
        - host: "dex.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "dex.${SECRET_DOMAIN}"
          secretName: tls.dex

    config:
      issuer: https://dex.${SECRET_DOMAIN}

      storage:
        type: kubernetes
        config:
          inCluster: true

      web:
        http: 0.0.0.0:5556

      frontend:
        theme: "tectonic"
        issuer: "holthome"
        issuerUrl: "https://${SECRET_DOMAIN}"
        logoUrl: http://icons.iconarchive.com/icons/icons-land/metro-halloween/512/Cool-icon.png

      expiry:
        signingKeys: "6h"
        idTokens: "24h"

      logger:
        level: debug
        format: json

      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
        alwaysShowLoginScreen: false

      enablePasswordDB: false

      connectors:
        # GitHub configure 'OAuth Apps' -> 'New OAuth App', add callback URL
        # https://github.com/settings/developers
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${SECRET_DEX_GITHUB_CLIENT_ID}
            clientSecret: ${SECRET_DEX_GITHUB_CLIENT_SECRET}
            redirectURI: https://dex.${SECRET_DOMAIN}/callback
            # 'orgs' can be used to map groups from Github
            # https://github.com/coreos/dex/blob/master/Documentation/connectors/github.md
            orgs:
              - name: holthome

      staticClients:
        - id: dex-k8s-authenticator
          name: dex-k8s-authenticator
          secret: ${SECRET_DEX_K8S_AUTHENTICATOR_CLIENT_SECRET}
          redirectURIs:
            - https://login.${SECRET_DOMAIN}/callback/

        - id: nextcloud
          name: nextcloud
          secret: ${SECRET_DEX_NEXTCLOUD_CLIENT_SECRET}
          redirectURIs:
            - https://nextcloud.${SECRET_DOMAIN}/apps/user_oidc/code
            - https://nextcloud.${SECRET_DOMAIN}/apps/oidc_login/oidc

        - id: oauth2-proxy
          name: oauth2-proxy
          secret: ${SECRET_DEX_OAUTH2_PROXY_CLIENT_SECRET}
          redirectURIs:
            - https://auth.${SECRET_DOMAIN}/oauth2/callback
            - https://requests.${SECRET_DOMAIN}/oauth2/callback

        - id: gitea
          name: gitea
          secret: ${SECRET_DEX_GITEA_CLIENT_SECRET}
          redirectURIs:
            - https://git.${SECRET_DOMAIN}/oauth2/dex/callback
            - https://git.${SECRET_DOMAIN}/user/oauth2/dex/callback

        - id: pomerium
          name: pomerium
          secret: ${SECRET_DEX_POMERIUM_CLIENT_SECRET}
          redirectURIs:
            - https://authenticate.${SECRET_DOMAIN}/oauth2/callback

        - id: step
          name: step
          secret: ${SECRET_DEX_STEP_CLIENT_SECRET}
          redirectURIs:
            - http://127.0.0.1:10000

        - id: k10
          name: k10
          secret: ${SECRET_DEX_K10_CLIENT_SECRET}
          redirectURIs:
            - https://k10.${SECRET_DOMAIN}/k10/auth-svc/v0/oidc/redirect

        - id: authentik
          name: authentik
          secret: ${SECRET_DEX_AUTHENTIK_CLIENT_SECRET}
          redirectURIs:
            - https://id.${SECRET_DOMAIN}/source/oauth/callback/dex/

        - id: vultr
          name: vultr
          secret: ${SECRET_DEX_VULTR_CLIENT_SECRET}
          redirectURIs:
            - https://my.vultr.com/openid/

    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 250Mi
