---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amcrest2mqtt
  namespace: home
spec:
  dependsOn:
    - name: mosquitto
      namespace: home
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: amcrest2mqtt
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: dchesterton/amcrest2mqtt
      tag: 1.0.16

    env:
      TZ: America/New_York
      AMCREST_HOST: ${SECRET_AMCREST2MQTT_AMCREST_HOST}
      AMCREST_USERNAME: ${SECRET_AMCREST2MQTT_AMCREST_USERNAME}
      AMCREST_PASSWORD: ${SECRET_AMCREST2MQTT_AMCREST_PASSWORD}
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_USERNAME: admin
      MQTT_PASSWORD: ${SECRET_MOSQUITTO_ADMIN_PASSWORD}
      HOME_ASSISTANT: "true"

    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 512Mi
