fail_fast: false
repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.27.1
  hooks:
  - id: yamllint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # - id: check-yaml
  #   args: [--allow-multiple-documents]
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-merge-conflict

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.2.0
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs

    #- repo: https://github.com/jumanjihouse/pre-commit-hooks
    #  rev: 2.1.4
    #  hooks:
    #  - id: shellcheck
    #    # args: [--severity=error]

- repo: https://git.iamthefij.com/iamthefij/ansible-pre-commit
  rev: v0.1.2
  hooks:
  - id: encryption-check
    files: ((^|/)encrypted-vault.y[a]{0,1}ml$|.vault$)
