---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-pv-media
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-config
    - name: cluster-repositories
    - name: manage-flux
  interval: 10m0s
  path: ./k8s/clusters/cluster-0/pv/media
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
