---
### Create Flux namespace
- name: Create Flux namespace
  command: kubectl create namespace flux
  ignore_errors: true

- name: Download fluxctl
  get_url:
    url: https://github.com/fluxcd/flux/releases/download/1.20.2/fluxctl_linux_amd64
    dest: /usr/local/bin/fluxctl
    mode: 0755

- name: Deploy Flux
  shell: |
    fluxctl install \
    --git-user={{ github_username }} \
    --git-email={{ github_username }}@users.noreply.github.com \
    --git-url=git@github.com:{{ github_username }}/{{ github_k8s_reponame }} \
    --git-branch={{ github_k8s_reponame_branch }} \
    --git-path=cluster \
    --namespace flux | kubectl apply -f -

- name: Get Flux identity
  command: "{{ item }}"
  with_items:
    - fluxctl identity
  register: flux_identity
  environment:
    FLUX_FORWARD_NAMESPACE: flux
  until: "'ssh-rsa' in flux_identity.stdout"
  retries: 30
  delay: 10

- name: Register Flux Identity with GitHub
  delegate_to: localhost
  script: "{{ REPO_ROOT }}/hack/add-repo-key.sh {{ github_username }} '{{ flux_identity.results[0].stdout }}' {{ github_k8s_reponame }}"
  register: register_result


### Flux CRDs require Prometheus CRDs in order to deploy properly. ###
- name: Deploy Prometheus ServiceMonitor CRD
  command: "{{ item }}"
  with_items:
    - kubectl apply -f https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-alertmanager.yaml
    - kubectl apply -f https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-podmonitor.yaml
    - kubectl apply -f https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheus.yaml
    - kubectl apply -f https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheusrules.yaml
    - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

- name: Add Flux Repo
  command: helm repo add fluxcd https://charts.fluxcd.io

- name: Apply Helm Operator CRDs
  command: kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml

- name: Deploy Helm Operator
  shell: |
    helm upgrade -i helm-operator fluxcd/helm-operator \
    --version 1.2.0 \
    --namespace flux \
    --set 'createCRD=false' \
    --set 'git.ssh.secretName=flux-git-deploy' \
    --set 'helm.versions=v3' \
    --set 'chartsSyncInterval=10m' \
    --set 'statusUpdateInterval=10m' \
    --set 'prometheus.enabled=true' \
    --set 'prometheus.serviceMonitor.create=false' \
    --set 'prometheus.serviceMonitor.interval=30s' \
    --set 'prometheus.serviceMonitor.scrapeTimeout=10s' \
    --set 'prometheus.serviceMonitor.namespace=flux' \
    --set 'dashboards.enabled=true'
