---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-exporter
  namespace: network
spec:
  interval: 5m
  releaseName: omada-exporter
  chart:
    spec:
      # renovate: registryUrl=http://charts.charliehaley.dev
      chart: omada-exporter
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: charlie-haley-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: chhaley/omada_exporter
      tag: "0.6.0"

    env:
      TZ: America/New_York

    omada:
      host: "https://omada-controller:8043"
      username: "exporter"
      password: "exporter"
      site: "Default"
      insecure: true

    resources:
      requests:
        memory: 500Mi
        cpu: 35m
      limits:
        memory: 750Mi
