---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 2.3.2
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: matrixdotorg/synapse
      tag: v1.58.1
    serverName: ${SECRET_PUBLIC_DOMAIN}
    publicServerName: matrix.${SECRET_DOMAIN}
    wellknown:
      enabled: true

    workers:
      media_repository:
        enabled: false
      default:
        volumes:
          - name: mautrix-facebook
            configMap:
              name: mautrix-facebook-config
              items:
                - key: registration.yaml
                  path: registration.yaml
          - name: matrix-slack
            configMap:
              name: matrix-slack-config
              items:
                - key: slack-registration.yaml
                  path: slack-registration.yaml
        volumeMounts:
          - name: mautrix-facebook
            mountPath: /data/mautrix-facebook
          - name: matrix-slack
            mountPath: /data/matrix-slack

    extraConfig:
      email:
        smtp_host: smtp.mailgun.org
        smtp_port: 587
        smtp_user: ${SECRET_MAILGUN_USERNAME}
        smtp_pass: ${SECRET_MAILGUN_PASSWORD}
        notif_from: "Your Friendly %(app)s homeserver <noreply@${SECRET_DOMAIN}>"

      enable_3pid_lookup: true
      allowed_local_3pids:
        - medium: email
          pattern: ".*"
        - medium: msisdn
          pattern: '\+1'
      account_threepid_delegates:
        msisdn: https://vector.im

      app_service_config_files:
        - /data/mautrix-facebook/registration.yaml
        - /data/matrix-slack/slack-registration.yaml

      oidc_providers:
        - idp_id: authentik
          idp_name: authentik
          discover: true
          issuer: "https://id.${SECRET_DOMAIN}/application/o/matrix/"
          client_id: "matrix"
          client_secret: ${SECRET_AUTHENTIK_MATRIX_CLIENT_SECRET}
          scopes:
            - "openid"
            - "profile"
            - "email"
          user_mapping_provider:
            config:
              localpart_template: "{{ user.preferred_name }}"
              display_name_template: "{{ user.name | capitalize }}"

    ingress:
      enabled: true
      traefikPaths: true
      className: traefik
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "false"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      tls:
        - secretName: tls.matrix
          hosts:
            - ${SECRET_PUBLIC_DOMAIN}
            - matrix.${SECRET_DOMAIN}

    postgresql:
      enabled: false

    externalPostgresql:
      host: matrix-synapse-postgres
      port: 5432
      username: synapse
      password: ${SECRET_MATRIX_POSTGRESQL_PASSWORD}
      database: "synapse"

    redis:
      enabled: true
      password: ${SECRET_MATRIX_REDIS_PASSWORD}

    signingkey:
      job:
        enabled: false

    persistence:
      enabled: false

    synapse:
      extraVolumes:
        - name: mautrix-facebook
          configMap:
            name: mautrix-facebook-config
            items:
              - key: registration.yaml
                path: registration.yaml
        - name: matrix-slack
          configMap:
            name: matrix-slack-config
            items:
              - key: slack-registration.yaml
                path: slack-registration.yaml
      extraVolumeMounts:
        - name: mautrix-facebook
          mountPath: /data/mautrix-facebook
        - name: matrix-slack
          mountPath: /data/matrix-slack
