---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1.14
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.1.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/carpenike/k8s-gitops/master/devops/flux/flux/flux-values.yaml
