---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./config-pvc.yaml
  - ./helm-release.yaml
  - ./volsync.yaml
# configMapGenerator:
#   - name: bazarr-scripts
#     files:
#       - ./scripts/autoscan.sh
# generatorOptions:
#   disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
