---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ealenn.github.io/charts
      chart: echo-server
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: ealenn-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ealen/echo-server
      tag: 0.5.2

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: "network-internal-auth@kubernetescrd"

      hosts:
        - host: echo-server.${SECRET_DOMAIN}
          paths:
            - "/"

      tls:
        - secretName: tls.echo-server
          hosts:
            - echo-server.${SECRET_DOMAIN}
