---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: teedy-postgres
  namespace: collab
spec:
  replicas: 1
  image: docker.io/library/postgres:11.16
  database:
    size: 5Gi
    storageClassName: ceph-block
  env:
    - name: POSTGRES_PASSWORD
      value: ${SECRET_TEEDY_POSTGRESQL_PASSWORD}
    - name: POSTGRES_REPLICATION_PASSWORD
      value: ${SECRET_TEEDY_POSTGRESQL_PASSWORD}
