---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: protonmail-bridge
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: shenxn/protonmail-bridge
      tag: 2.1.3-1
    env:
      TZ: "America/New_York"
    ingress:
      main:
    persistence:
      config:
        enabled: true
        existingClaim: protonmail-bridge-config-pvc
