---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./externalsecret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: recyclarr-config-tpl
    files:
      - ./configs/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: recyclarr
      app.kubernetes.io/instance: recyclarr
