---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  releaseName: qbittorrent
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2

    settings:
      automaticPortSetup: false

    podAnnotations:
      setGateway: "true"

    hostname: qbittorrent

    env:
      TZ: "America/New_York"

    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_QBITTORRENT_ADDRESS}"
        ports:
          bittorrent:
            enabled: true
            port: 56059
            protocol: TCP
            targetPort: 56059
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-internal-auth@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qb.${SECRET_DOMAIN}"
            secretName: tls.qb

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: qb-config-pvc

      nfs-nas-media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nas.${SECRET_DOMAIN}"
            path: /mnt/tank/share
        mountPath: /media
        readOnly: false

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi

    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m

    # additionalContainers:
    #   - name: exporter
    #     image: esanchezm/prometheus-qbittorrent-exporter:latest
    #     imagePullPolicy: IfNotPresent
    #     env:
    #       - name: QBITTORRENT_HOST
    #         value: "http://localhost"
    #       - name: QBITTORRENT_PORT
    #         value: "8080"
    #       # - name: QBITTORRENT_USER
    #       #   value: "${SECRET_QB_USER}"
    #       # - name: QBITTORRENT_PASS
    #       #   value: "${SECRET_QB_PASSWORD}"
    #       - name: EXPORTER_PORT
    #         value: "9022"
    #       - name: EXPORTER_LOG_LEVEL
    #         value: "INFO"
    #       - name: METRICS_PREFIX
    #         value: "qbittorrent"
    #     ports:
    #       - name: metrics
    #         containerPort: 9022
    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
