---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  CLUSTER_NAME: cluster-0
  CLUSTER_ID: "1"

  # Router Gateway IP
  GATEWAY_IP: "10.20.0.1"

  # Networks
  NETWORK_SERVERS_CIDR: 10.20.0.0/16
  NETWORK_BGP_SVC_CIDR: 10.45.0.0/16
  NETWORK_K8S_POD_CIDR: "10.244.0.0/16"
  NETWORK_K8S_SERVICE_CIDR: "10.96.0.0/16"
  NETWORK_K8S_CLUSTER_CIDR: "10.244.0.0/16"
  NETWORK_MANAGEMENT_CIDR: "10.20.0.0/16"

  # Loadbalancer IP's
  LB_TRAEFIK: 10.45.0.1
  LB_PROMTAIL: 10.45.0.2
  LB_BLOCKY: 10.45.0.3
  LB_UNIFI: 10.45.0.4
  LB_HASS: 10.45.0.11
  LB_PLEX: 10.45.0.20
  LB_MOSQUITTO: 10.45.0.10

  # Service IPs
  SVC_NGINX_ADDRESS: "10.45.10.10"
  SVC_TRAEFIK_ADDRESS: "10.45.20.10"
  #SVC_VERNEMQ_ADDRESS: "10.45.10.11"
  SVC_MOSQUITTO_ADDRESS: "10.45.10.11"
  SVC_GITEA_ADDRESS: "10.45.10.12"
  SVC_K8S_GATEWAY_ADDRESS: "10.45.10.13"
  SVC_BLOCKY_ADDRESS: "10.45.10.13"
  SVC_HASS_ADDRESS: "10.45.10.15"
  SVC_LOKI_ADDRESS: "10.45.10.16"
  SVC_VECTOR_AGGREGATOR: "10.45.10.16"
  SVC_RESILIO_SYNC_ADDRESS: "10.45.10.18"
  SVC_QBITTORRENT_ADDRESS: "10.45.10.19"
  SVC_OMADA_ADDRESS: "10.45.10.20"
  SVC_COREDNS_ADDRESS_EXTERNAL: "10.45.10.53"
  SVC_PLEX_ADDRESS: "10.45.100.100"
  VPN_PORT: "51820"
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "56059"
