---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager
- external-dns
- external-secrets
- external-snapshotter
- kube-prometheus-stack
- registry-creds
- rook-ceph
- traefik

