---
REPO_ROOT: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
common_timezone: America/New_York
cri_plugin: docker
common_log2ram_enabled: false
cluster_extra_sans:
  - k8s.holthome.net
cluster_control_plane_endpoint: "k8s.holthome.net:6443"
cluster_pod_subnet: "10.42.0.0/16"
cilium_helm_version: 1.8.3
cilium_image_version: v1.8.3
github_username: carpenike
github_k8s_reponame: k8s-gitops
github_k8s_reponame_branch: master
