---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stash
  namespace: stash
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~v1
spec:
  releaseName: stash
  chart:
    repository: https://charts.appscode.com/stable/
    name: stash
    version: v0.9.0-rc.4