---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-namespace
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security"
  prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: security-dex
#   namespace: flux-system
#   labels:
#     component.cluster-0/part-of: definitions
# spec:
#   dependsOn:
#     - name: security-namespace
#   path: "./cluster/clusters/cluster-0/security/dex"
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: security-glauth
#   namespace: flux-system
#   labels:
#     component.cluster-0/part-of: definitions
# spec:
#   path: "./cluster/clusters/cluster-0/security/glauth"
#   prune: true
#   dependsOn:
#     - name: security-namespace
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: security-authelia-redis
#   namespace: flux-system
#   labels:
#     component.cluster-0/part-of: definitions
# spec:
#   path: "./cluster/clusters/cluster-0/security/authelia/redis"
#   prune: true
#   dependsOn:
#     - name: security-namespace
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: security-authelia
#   namespace: flux-system
#   labels:
#     component.cluster-0/part-of: definitions
# spec:
#   path: "./cluster/clusters/cluster-0/security/authelia/app"
#   prune: true
#   dependsOn:
#     - name: security-namespace
#     - name: security-glauth
#     - name: security-authelia-redis
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-vaultwarden
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security/vaultwarden"
  prune: true
  dependsOn:
    - name: security-namespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-external-secrets
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security/external-secrets/app"
  prune: true
  dependsOn:
    - name: security-namespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-onepassword
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security/external-secrets/stores/onepassword"
  prune: true
  dependsOn:
    - name: security-namespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-oauth2-proxy-redis
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security/oauth2-proxy/redis"
  prune: true
  dependsOn:
    - name: security-namespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: security-oauth2-proxy
  namespace: flux-system
  labels:
    component.cluster-0/part-of: definitions
spec:
  path: "./cluster/clusters/cluster-0/security/oauth2-proxy/app"
  prune: true
  dependsOn:
    - name: security-namespace
