---
apiVersion: v2
description: A KaH-common powered chart template
name: kah-common
version: 1.0.0
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.0.1
  - name: postgresql
    version: 10.13.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
