---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ceph-block-pool.yaml
- ceph-cluster.yaml
- ceph-file-system.yaml
- ceph-block-storage-class.yaml
- ceph-volume-snapshot-class.yaml
- ceph-object-store.yaml
- ceph-bucket-storage-class.yaml
- ceph-object-bucket.yaml
