---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../global/flux/repositories/helm
  - ananace-charts.yaml
  - appscode-charts.yaml
  - authentik-charts.yaml
  - banzaicloud-charts.yaml
  - bitwardenrs-charts.yaml
  - charlie-haley-charts.yaml
  - cilium-charts.yaml
  - codecentric-charts.yaml
  - coredns-charts.yaml
  # - dacruz21-charts.yaml
  - democratic-csi-charts.yaml
  - dex-charts.yaml
  - dexidp-charts.yaml
  - ealenn-charts.yaml
  - fairwinds-charts.yaml
  - falco-security-charts.yaml
  - gatekeeper-charts.yaml
  - gitea-charts.yaml
  - grafana-charts.yaml
  - grafana-loki-charts.yaml
  - hajimari-charts.yaml
  - influxdata-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - k8up-charts.yaml
  - kasten-charts.yaml
  - kubernetes-external-secrets-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - kubernetes-stable-charts.yaml
  - lwolf-charts.yaml
  - mailu-charts.yaml
  - minio-charts.yaml
  - nicholaswilde-charts.yaml
  - nextcloud-charts.yaml
  - oauth2-proxy-charts.yaml
  - ory-charts.yaml
  - pomerium-charts.yaml
  - rook-ceph-charts.yaml
  - timberio-charts.yaml
  - vector-charts.yaml
  - vernemq-charts.yaml
  - weaveworks-kured-charts.yaml
  - yourls-charts.yaml
