---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-network-omada
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-namespaces
    - name: rook-ceph-cluster
    - name: core-traefik
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/apps/network/omada"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-network-unifi
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-namespaces
    - name: rook-ceph-cluster
    - name: core-traefik
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/apps/network/unifi"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-network-external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-namespaces
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/apps/network/external-dns"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-network-dns-update
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-namespaces
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/apps/network/dns-update"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-network-adguard
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-namespaces
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/apps/network/adguard"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
