---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-collab.yaml
  - apps-comms.yaml
  - apps-network.yaml
  - apps-home.yaml
  - apps-media.yaml
  - apps-security.yaml
  - apps-vpn-gateway.yaml
  - core-cert-manager.yaml
  - core-certificates.yaml
  - core-chrony.yaml
  - core-cilium.yaml
  - core-error-pages.yaml
  - core-kasten-io.yaml
  - core-metrics-server.yaml
  - core-monitoring.yaml
  - core-nfd.yaml
  - core-rbac.yaml
  - core-rook-ceph.yaml
  - core-traefik.yaml
