masters:
  hosts:
    h2-0:
      hostname: h2-0.holthome.net
      ansible_host: 10.20.10.16
workers:
  hosts:
    r610-0:
      hostname: r610-0.holthome.net
      ansible_host: 10.20.10.10
      ansible_user: ubuntu
    r610-1:
      hostname: r610-1.holthome.net
      ansible_host: 10.20.10.11
      ansible_user: ubuntu
    r610-2:
      hostname: r610-2.holthome.net
      ansible_host: 10.20.10.12
      ansible_user: ubuntu
    r720-0:
      hostname: r720-0.holthome.net
      ansible_host: 10.20.10.15
      ansible_user: ubuntu
    # n2-0:
    #   ansible_host: n2-0.holthome.net

longhorn:
  hosts:
    r610-0:
      hostname: r610-0.holthome.net
      ansible_host: 10.20.10.10
      ansible_user: ubuntu
    r610-1:
      hostname: r610-1.holthome.net
      ansible_host: 10.20.10.11
      ansible_user: ubuntu
    r610-2:
      hostname: r610-2.holthome.net
      ansible_host: 10.20.10.12
      ansible_user: ubuntu
  vars:
    lvm_groups:
      - vgname: longhorn-vg
        disks:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
        opts: i3
        create: true
        lvnames:
          - lvname: lv0
            size: 100%FREE
            create: true
            filesystem: ext4
            mount: true
            mntp: /var/lib/longhorn
    manage_lvm: true

nfs:
  hosts:
    r720-0:
      hostname: r720-0.holthome.net
      ansible_host: 10.20.10.15
      ansible_user: ubuntu
  vars:
    nfs_exports:
      - /mnt/tank/share 10.20.0.0/16(rw,async,no_subtree_check,no_root_squash)

# arm:
#   hosts:
#     n2-0:
#       ansible_host: n2-0.holthome.net

cluster:
  children:
    masters:
    workers:

storage:
  children:
    ceph:
    nfs:

vault:
  hosts:
    localhost:
      ansible_connection: local

# routers:
#   hosts:
#     vyos:
#       hostname: vyos.holthome.net
#       ansible_host: 10.20.0.1
