helmOperator:
  create: false
git:
  url: "git@ssh.dev.azure.com:v3/ryholt/HomeAutomation/k8s-gitops"
registry:
  rps: 1
  burst: 1
# memcached:
#   tolerations:
#   - key: "arm"
#     operator: "Exists"
additionalArgs:
  - --connect=ws://fluxcloud
prometheus:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
