apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: home-assistant-secrets
  namespace: home
stringData:
  HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:cqPWi55cRUgV5tOaLACC4DEQ,iv:Y4/7QgKDtzPehCiE5Rn1vnlvbMu2NODY0A0JaT7oEiU=,tag:WHJTSsa1Xmo09uBDuDmSBw==,type:str]
  HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:DQQYPj0qV1JXiZFzfRLIeexG,iv:bkzrtif0hyTFMqFTVUGKZqZ51/MB0jKvmtIpqJEHpBU=,tag:b+TZ5/pX8ZIOE2mJuzQflQ==,type:str]
  HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:qviIWxmC,iv:zZyzeZLAqUIT8bUKYQDSvDDV3q382qxRaa/Xjh6g1GQ=,tag:VUfCWfk2yW5MEQyqYG3CNg==,type:str]
  HASS_EXTERNAL_URL: ENC[AES256_GCM,data:PTGIj1yvvqA872iYpjRVySB7z2sQ7Js=,iv:ntgs429egR00S4MkGjGvqx+kI4dGoBxjGpzfWYtMQvM=,tag:7LEk3b96mbCoQ5l41XtHGg==,type:str]
  HASS_RECORDER_POSTGRESQL: ENC[AES256_GCM,data:3cnrQEGewwXCrT3IS9vyQlr+AcclPpud1lhIc5m/lrrotVtYgEKuME9H22e42niZ1qlAhCIrzDBW2tT/y5ESHstxu1g3,iv:OivRgFX4TP3mOD2NJobaoVEZVA/LqhUXuiEnnJu2gs4=,tag:pipEme3GSvPslZqL/PDKpg==,type:str]
  HASS_ECOBEE_API_KEY: ENC[AES256_GCM,data:Le1fFLpHGEOjKfg9u/LzdAqiN8z+KT1R+G8YKbMM5k4=,iv:/CS7y7LlAWruiF3h6beXHMEODFm7zmCInu0K/Mevmho=,tag:xqhUH6uR/vf6sPF8zaC35Q==,type:str]
  HASS_AUGUST_PASSWORD: ENC[AES256_GCM,data:9XL7PJKv5SCQRA==,iv:ILimDVeb3qfOtPWCRvNMeN6/9O2B74hrfyTZ/y3y11o=,tag:EfnGleWeUTtzNgFUxluEUg==,type:str]
  HASS_AUGUST_EMAIL: ENC[AES256_GCM,data:VPD70/aOKI3terHOJsH57S4=,iv:BxWllKm7EMarjJrzOZ8EYGmGMCdNrltN/uhdc1t/lEc=,tag:fxurKuzQiVMW8UtxILltPQ==,type:str]
  HASS_NEST_CLIENT_ID: ENC[AES256_GCM,data:pKs25/hrJdz5Usvf3ZURkxV1M7xLwFL1Ep+Bt2wU7A7+FTN+5tYLcxKLEZSY+wcPNtqzTh/3qfIFkY5KRgw2TPq9uzYTGiE1,iv:pur3m0O8wMLXxXxroYBueaWUv1bnLl9bbWIzLAMoAoQ=,tag:fbD5PrNd6vDRlhTcPmS76g==,type:str]
  HASS_NEST_CLIENT_SECRET: ENC[AES256_GCM,data:QPIO6H5PGJ85S+f+OGrcLm2A4ANWmxZX,iv:C7JnQkMX3byPCbFOR7E4NNQgcg60lNNcHKy/jChnKtc=,tag:+yJcxBMCqc2cL8TwH2ohGQ==,type:str]
  HASS_NEST_PROJECT_ID: ENC[AES256_GCM,data:j6KrMeLEMMF/JMs7qKv1sBJXhWbyQfiIIA/gVEtvNtdj9nZ7,iv:zKILw1UpWfDG/diiInwAWJW2+OWzq7YAPwpklfLX1+0=,tag:ol50m0etcF4lhl0LCeF4Gw==,type:str]
  HASS_NEST_SUBSCRIBER_ID: ENC[AES256_GCM,data:EVgZtFNA8HhxJdDPE4dyetbGAw9eXk+scklrfSrhJ1B6RfHIItHQmSEDZrqywmuWYxUzflCxq0m+,iv:HbRFvuYiUXGJNb0z5lnDKg3ThWuaNi11LnseYwjzxWU=,tag:pk2H1V7Hs4LCIkeuI12K4Q==,type:str]
  HASS_SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:5muxiZaq/dJ5jUUGep+8KQ2rFJBzel1mpSgBtcEYO3A=,iv:USjHKXDq3MQ3kYHdkLNwdpgqoImdCmRhzScT8fsjZ0k=,tag:DyHaa5W60PB4UYOoGDYB+Q==,type:str]
  HASS_SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:qG5Ne5e2h8uGIK5+VTOm8RDwJkACy65QNbdhja684PA=,iv:280wiRTUYRrEePm3+nuzIccVWd23tpkKpKmn8+9r4Ow=,tag:UrxNC1csRHMd13iStS17rA==,type:str]
  HASS_BACKPATIO_CAMERA_MAIN: ENC[AES256_GCM,data:znHhwzU5upnyEiR+D7SOuhge+msTycF4XO5UpnJAGvv1FiwaW5YCRfMaHDfDYpsNCToDopfrWydvhBAjW+5ngFFL8PeBhic5yzRNaNnY4XXSjARZB+3w46V5BFoC3xhaPSYL2ly0BeMDmmOg5RDFp6e62ss=,iv:9gH/rZ5HfuUrJRpEh5F3JNzZW2rYPB31hZZCYyfIlZo=,tag:+/22LWAm0q+I/ULADX6FUg==,type:str]
  HASS_BACKPATIO_CAMERA_SUB: ENC[AES256_GCM,data:7wRSG4MpiDdnLeyrU6Wc5QEjU1ApMdZ9nqFyjZqS3c05ZeICDRo8H/DTtZnhcDS1WmIOYB7ggpIunw1Zazcy0dHhoYRzJa6wJl528Ald8T3+guBwRwDshXL+MSV+FeQtJ3Hao+T2R6Yh5Y48+p53uHkNSg==,iv:O5L8vTEiU5g26oPgZGgGRtmgSc9nLlLN/NpSTTC9Jgw=,tag:mGOHlxmM2XJ48VVPxJDshQ==,type:str]
  HASS_SECRET_DARK_SKY_API_KEY: ENC[AES256_GCM,data:7/0ECwIhKBEp22/6ZkIMfD/9W2iExfd+q2R65qyGS9c=,iv:tU6s5Cve0/HtT+75HBvtVAbU+BroLgOqICmUx0ojWcs=,tag:Esnut7uKIK/ijeCEzPmH6w==,type:str]
  HASS_SECRET_MIELE_CLIENT_ID: ENC[AES256_GCM,data:zYHCCAJqaxMi8OKA6Lmd7Q6b4OqQX4cJOmC2cMoXfZ2CRqGi,iv:a1GxPh1d74KQBwQnJQNvsaqg00GWseXm16pRpa10Kmw=,tag:HQAIVRxRQOl/kNEsxv3EmA==,type:str]
  HASS_SECRET_MIELE_CLIENT_SECRET: ENC[AES256_GCM,data:ekF1pOfZt2QIppb9TpYwFujgSgf9rnMUaKabMD6ZUeA=,iv:mB7esiT6Fm8yoBnzPIqJ0BMaXxTDu/vKwbPoRc//IQk=,tag:Nera4ldiT6aAxBLG19Ryvg==,type:str]
  HASS_SECRET_SP_DC: ENC[AES256_GCM,data:zHUvCP5C0U+WXOho98bTjhRQdtJRSxnhcKg3/vI/xRRX/uuNkPmMK8pdZ/M/+kORTbYSvZjjoujqAKH0Y8PJh3Zy92/mtbEn5dLbY7XoajSo1omyzVknZ+crDEHl7EVpeJjrFmPZGhvDF05zm/E=,iv:mCIOZKny7bVG5pOP1F4xvkfeT4swTMGGey2j2xTZe2M=,tag:OukyCBEO+t7b5fNgB2VflQ==,type:str]
  HASS_SECRET_SP_KEY: ENC[AES256_GCM,data:9DlMXcU2vUfuYAwiQhaM85+AaFk2e+wPgQHsASYg8IN8/brB,iv:iZXG51tyUTWa7l84JETu3jK+3uiAQSrQzvMooRTd2H8=,tag:ujdgEWHJEDUDSnUP6Sz1vQ==,type:str]
  HASS_AMCREST_USERNAME: ENC[AES256_GCM,data:zUfT8oA=,iv:/6T5F+b1+mgORPHo7bJE4VFCO61mB7fgjyNBHaadLjA=,tag:8VPtiOXbySm8AC8NUU3+eg==,type:str]
  HASS_AMCREST_PASSWORD: ENC[AES256_GCM,data:AQ4n7zzX/XGTHgR3,iv:6oEeJz6+7WyNj+2+nLPeIRfztt9fvZlYKV66tt547eI=,tag:44R9I0K7PfWI0Dd+nfZ5UA==,type:str]
  HASS_AMCREST_FRONTDOOR_RTSP_STREAM: ENC[AES256_GCM,data:M2Wn+ksVQcQoQo9O+SSZHXnGk/bGoIj6vN7p8SILkLWtE4mE4x4JjtrmqHZnxsKvYhgwMaopt2xmKiAERhgSilNdS+DnHNEE9yGoNJ9Tu39tbNgy5afH89rXCA==,iv:pbfW+vaWZjlwaCcXRYvpa2etAT1Z+CWkgFN/xvZUzM8=,tag:kBc02zOJPA1FrMNeXKBO+g==,type:str]
  HASS_HIKVISION_PATIO_RTSP_STREAM: ENC[AES256_GCM,data:Fuc8od86eoBkz8bSAtIVFFSO1wwT0uAv9mMFA6kL+bUsnp3SuoQ4mYeRXiHx7mRdIWTeupekGx+L5hkXoFU1a5wY,iv:AqQdevMkVWZmTkB7qcCK5+Eidsl9/CQC9zIkRxUtSgY=,tag:/tvSiMntL69yFsF/KQteAQ==,type:str]
  HASS_MQTT_MOSQUITTO_PASSWORD: ENC[AES256_GCM,data:Cc7W1C/D9q/3uzVqD58H+YO+t74v0+CK,iv:cShGNLqerf/xZVMDQEZvIHZ7PYU8eBVlBJTAbsrUKbs=,tag:6A2JwRYcEHLozL0MQD34aw==,type:str]
  HASS_SECRET_NONA_LONGITUDE: ENC[AES256_GCM,data:vslVwCykuyKelA==,iv:ncqOZjRl4VMF8e3ea1SPfOv1QDO7qW4jHxcEART+jZY=,tag:mI7P8RTLntRQn2ugG6BCaA==,type:str]
  HASS_SECRET_NONA_LATITUDE: ENC[AES256_GCM,data:osJP1Jy8J/q8,iv:BuqNQjgkgDpSy8R3K288pJZ3UDZDt462RandXYGDty8=,tag:i+FzL9dz3rLvnJlJImF3/Q==,type:str]
  HASS_SECRET_ICLOUD_PASSWORD: ENC[AES256_GCM,data:+hUh9uIM3/qSp/MQndVvMzo//A==,iv:Aj7fhAUSVSTME3NpDVBGdhSWlfziKxGyg18B/649YyI=,tag:pj8yjpGtK4TA2fkBYTPqAQ==,type:str]
  HASS_SECRET_ICLOUD_USERNAME: ENC[AES256_GCM,data:KD9kGf/ivsYALTxAnVx+Lis=,iv:tv6YU+uT//iv2TXZ7w6suCKCJXiP1zFKKUoLNVR29mg=,tag:QtlG4vTGgJUtWyChXoprhw==,type:str]
  HASS_FLAIR_CLIENT_ID: ENC[AES256_GCM,data:RPqTSH0ah3IypfnUDK38HbiUqScG0IMZqPgvvLWDJbmcQqwEslB44A==,iv:gTia8PspbRnr2vhsE8LToeW4qXkjMHVgu9cb2dkv1Qw=,tag:8P7aOCugZ+sE1Skph2bQRw==,type:str]
  HASS_FLAIR_CLIENT_SECRET: ENC[AES256_GCM,data:zwVmwjKbNggoxx2BKhOW0LdZBI38HmSJukSierLvY9vejeGUurrgoWB/7kaNcV+jbR+K85cyK0jSFtqc,iv:26dPsh6j8bW+/OPG52DhvhrFQPeAEQCGeOxeP3lXtsw=,tag:eqHbuVGjHyVru5C6XSeR3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-06-19T12:12:11Z"
  mac: ENC[AES256_GCM,data:EE5UMJPNgbMZ3o8coJcCYgE4ryxsu1GS3ghsU2NGJZSNwAQtBL8xE+/i9U9YvrBnEwClEL4crXMNDgFfyZ7g+HkNn+g5lU/jyMzKNZGvx97eOcrhtdawnMqNs2JU716IaNOEl7gReDUGjG/fhF8jtNAhew8eW6C3RVz+818UHSM=,iv:ERsmJion5Ru8TZdqJR8iDIOahD4Vu9x3KcLP1kzQr7E=,tag:QxBb2Ya+yl/Qdmb9ANFgPQ==,type:str]
  pgp:
    - created_at: "2021-06-03T18:15:35Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA8oSIqtHvng8AQ//VYou9Eravaa7MhT+Cb7bejpIVoz71fMGheNmU19IPhLL
        Jzg+++h79sFG5Bu2rx8RD6IEWanwI5lCbXdOfSisGgAyoQwd3Yk7mUkwBT8e2pai
        MT1U9g62qxU2q4Gtl2pyXeXUXHK4wmtZlioGJlXuKpieViemypfhLy2l65pZjQv0
        3XWerKZUSvjNcYRH5lR9a48DO6Y/xKbWIkZg3HFx245+KfsUb7Wv6HSaMHPRwQLc
        RHzAFq2r37E8j2wJvb4pBFalzL/xX4X6QFD3Zb550JlJLHfkThWAnkyjUQrQdGIJ
        l/4SiVL7YrLkXg3BoYNwf2rR8TmdQnIOG41d09k1hiNq4C4FGPEF9FmNeT2jOGHU
        f5h14kS5ZzR3uPZE7Y7a59oaRWDD16jgQgXtrgWD8/afQ8CRh5VSxdHcsSZUvX/U
        Da31loR8IRWrDIgbRflz96Vn3mb4E2o6YLqjhHreF1Xl6//RSHE48ub5AGV9UPTf
        60rjV0RrOVaXTZ5Tj7SgS2H0M4crYywW6BDT9gPP2Lc5CDcM/Ee07RwUNbjfaA1j
        lp3SfS/muLHpYOb5bdPBYQdvtk7kBvQsRIFN8KqanHgwXKsndp0siAp/5lDDTlPo
        dREz7eXW59hYPlG2KnMj2fkIncinEluYRcMiGgE+xMn5itTyjvsh8o+G/oQ4DFPS
        XAG+8MIqtOLYvUfA6+ZKWYpv5bHf9Q6yCRJc9G13SKfriK/4pMQDcAqFPUwtSxWl
        +aoUIm8DUMJi8iwzCIq5kg7sCj2D0eD94d+xvByo5g22Mg6VfejUIgXw1oX0
        =pwiZ
        -----END PGP MESSAGE-----
      fp: DA8002060402EC39B195451D5CED80362B5A4EF2
    - created_at: "2021-06-03T18:15:35Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA8ORz3KkY6O4ARAAouC5dHq/MY3PJQgr3dBkWOCCEO4U8jxCTx3GJGf/kokv
        hCBLX4Mpvc/Ho7yQ31bl0y9KoT/JRSK30SgWHlLh6yBSRzcYsKSsJ106Rw/fW4iZ
        zNP3ee/k5Xh8eMK/19zWUC1GDWQnxEGi1ayWHaZU97YtAHupQd0xauNaivYIbKzN
        8GYFg/wfvZ9xrr0+X/aZSoJN0OJqFU+Xm0S1GISLHddZ4+gD1u9zws+ROrD6etW/
        JQi3c8W7AAKMmZDsP5Qx14FhQPHTvCeJXq61iOip2D8liqN+1ldrlWiWRitNa4qm
        3Nj6Sjiebbxf2/NirdO5b3CRg/4knkY6aS6XawiOeiaqdvKoVyppqjGXXzRsR4bL
        gZmgsu0UINOEfl1sjEj3UhwqpxC3U99CQNZP2kmUEhGIQHSHFH9fGw1fDHXDOSQL
        YsReHXOHXdGUT89kpk+Je4XmEInZtd4CWTaCalrK7c74PGFAH9sQ4kBj8aoXp92Z
        JcNBoHKCKP12wGHex/g4VFwD6KeDlANmyUo8f6peiOJ/dYL7GAf+0KVBDSFlirPY
        F5f3E89nBkdWlLXxFmNIGvVrZ4p4bEysrmHv/Nct0atcw1SuP6VVemdL5NWo9PPf
        Z8qxgsVNqa8apHD5BSKLM9gknq+o5cXUN7z4gWKRQ/IGnskww4dpKjLU++LfCafS
        XAGNs6//e8H5YQmk+6XRGPUiLPPMu9FRghSSxeZQjrg6QydHEcXiFNmY6Q1xapL8
        CdbwghgTsjVKqp0lEQ5mroSMZxBCMtZ1la/DAmke0P5/E1alm9Xw7AvXDDBT
        =Eiy9
        -----END PGP MESSAGE-----
      fp: 76DAFEBE0E21604BB9F2D6C11850C928A0D756C8
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
