---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: home
spec:
  releaseName: mealie
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
      tag: v0.5.6
    env:
      TZ: "America/New_York"
      DEFAULT_EMAIL: ryan@ryanholt.net
      BASE_URL: https://meals.${SECRET_DOMAIN}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # traefik.ingress.kubernetes.io/router.middlewares: "network-internal-auth@kubernetescrd"
        hosts:
          - host: "meals.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "meals.${SECRET_DOMAIN}"
            secretName: tls.mealie
    persistence:
      config:
        enabled: true
        existingClaim: mealie-config-pvc
