---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./gatus.yaml
  - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: wizarr
      app.kubernetes.io/instance: wizarr
