---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mta-sts
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: network
  values:
    image:
      repository: joseluisq/static-web-server
      tag: 2.11.0-alpine
    controller:
      replicas: 3
    nameOverride: mta-sts
    env:
      SERVER_PORT: 80
      SERVER_ROOT: /public
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "mta-sts.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: mta-sts-cert
            hosts:
              - "mta-sts.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /public/.well-known
        volumeSpec:
          configMap:
            name: mta-sts
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
