apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ombi-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/ombi/ombi-helm-values
  type: Opaque