---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-media-repo
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-media-repo
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: turt2live/matrix-media-repo
      tag: v1.2.12

    config:
      datastores:
        - type: s3
          enabled: true
          forKinds: ["all"]
          opts:
            tempPath: "/tmp/mediarepo_s3_upload"
            endpoint: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
            ssl: false
            accessKeyId: ${SECRET_MATRIX_MEDIA_S3_ACCESS_KEY_ID}
            accessSecret: ${SECRET_MATRIX_MEDIA_S3_ACCESS_SECRET}
            bucketName: "matrix-media"

    admins:
      - "@ryan:${SECRET_PUBLIC_DOMAIN}"

    homeservers:
      "matrix.${SECRET_DOMAIN}":
        csApi: 'http://matrix-synapse:8008'
        backoffAt: 10
        adminApiKind: 'matrix'
        identicons:
          enabled: false

    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
        - host: matrix.${SECRET_DOMAIN}
          paths:
            - "/_matrix/media"
      tls:
        - secretName: matrix-cert
          hosts:
            - matrix.${SECRET_DOMAIN}

    postgresql:
      enabled: true
      sslMode: disable
      postgresqlPassword: ${SECRET_MATRIX_POSTGRESQL_PASSWORD}
      postgresqlUsername: synapse
      postgresqlDatabase: synapse
      persistence:
        enabled: true
        existingClaim: matrix-media-repo-postgresql-pvc

    persistence:
      enabled: false

  # valuesFrom:
  #   - kind: ConfigMap
  #     name: matrix-media-ceph-bucket
  #     valuesKey: BUCKET_NAME
  #     targetPath: config.datastores.opts.bucketName
  #   - kind: ConfigMap
  #     name: matrix-media-ceph-bucket
  #     valuesKey: BUCKET_HOST
  #     targetPath: config.datastores.opts.endpoint
  #   - kind: Secret
  #     name: matrix-media-ceph-bucket
  #     valuesKey: AWS_ACCESS_KEY_ID
  #     targetPath: config.datastores.opts.accessKeyId
  #   - kind: Secret
  #     name: matrix-media-ceph-bucket
  #     valuesKey: AWS_SECRET_ACCESS_KEY
  #     targetPath: config.datastores.opts.accessSecret
