---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: littlelink
  namespace: collab
spec:
  interval: 5m
  releaseName: littlelink
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: littlelink-server
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/techno-tim/littlelink-server
      tag: latest
    env:
      TZ: "America/New_York"
      META_TITLE: Ryan Holt
      META_DESCRIPTION: Ryan Holt Link Page
      META_AUTHOR: Ryan Holt
      THEME: Dark
      FAVICON_URL: https://avatars.githubusercontent.com/u/1302442?v=4
      AVATAR_URL: https://avatars.githubusercontent.com/u/1302442?v=4
      AVATAR_2X_URL: https://avatars.githubusercontent.com/u/1302442?v=4
      AVATAR_ALT: Ryan Holt
      NAME: Ryan Holt
      BIO: Hey! Feel free to reach out to me on any of the below.
      GITHUB: https://github.com/carpenike
      LINKED_IN: https://linkedin.com/in/ryanholt
      TWITTER: https://twitter.com/ryanholt
      EMAIL: ryan@ryanholt.net
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "me.${SECRET_SHORT_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "me.${SECRET_SHORT_DOMAIN}"
          secretName: littlelink-cert
