---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home-0
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.108.0-b.3
      pullPolicy: Always

    persistence:
      config:
        enabled: true
        existingClaim: adguard-0-config-pvc

    env:
      TZ: "America/New_York"

    service:
      main:
        port:
          port: 3000

      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_ADGUARD_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "adguard.${SECRET_DOMAIN}"
            secretName: tls.adguard

    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 2000Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home-1
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.108.0-b.3
      pullPolicy: Always

    persistence:
      config:
        enabled: true
        existingClaim: adguard-1-config-pvc

    env:
      TZ: "America/New_York"

    service:
      main:
        port:
          port: 3000

      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_ADGUARD_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    ingress:
      main:
        enabled: false

    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 2000Mi
