---

- name: Check for uninstall file
  stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: p
  when: ( type == 'worker')

- name: Uninstall K3S Worker on all nodes
  command: "{{ item }}"
  become: yes
  with_items:
    - /usr/local/bin/k3s-agent-uninstall.sh
  register: k3s_agent_result
  when: ( type == 'worker' and p.stat.exists == true )

- name: Validate k8s workers uninstalled successfully
  debug:
    var: k3s_agent_result.msg

- name: Check for uninstall file
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: p
  when: ( type == 'master')

- name: Uninstall K3S Master
  command: "{{ item }}"
  become: yes
  with_items:
    - /usr/local/bin/k3s-uninstall.sh
  register: k3s_master_result
  when: ( type == 'master' and p.stat.exists == true )

- name: Validate k8s master uninstalled successfully
  debug:
    var: k3s_master_result.msg

- name: Remove all docker containers
  ignore_errors: yes
  shell: "docker rm -f $(docker ps -a -q)"
