mqtt:
  host: mosquitto
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7
    dog:
      min_area: 1000
      max_area: 10000
      threshold: 0.7
# ffmpeg:
#   hwaccel_args:
#   - -hwaccel
#   - vaapi
#   - -hwaccel_device
#   - /dev/dri/renderD128
#   - -hwaccel_output_format
#   - yuv420p
cameras:
  # --
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_PATIO_USER}:{FRIGATE_CAMERA_PATIO_PASSWORD}@{FRIGATE_CAMERA_PATIO_HOST}:554/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://{FRIGATE_CAMERA_PATIO_USER}:{FRIGATE_CAMERA_PATIO_PASSWORD}@{FRIGATE_CAMERA_PATIO_HOST}:554/Streaming/Channels/1
          roles:
            - record
            - rtmp
    detect:
      height: 360
      width: 640
      fps: 10
    objects:
      filters:
        person:
          min_area: 1500
          max_area: 100000
          threshold: 0.75
          min_score: 0.60
    record:
      enabled: True
      retain_days: 14
      events:
        objects:
          - person
          - dog
    snapshots:
      enabled: True
      timestamp: False
      retain:
        default: 14
    zones:
      backyard:
        coordinates: 640,0,640,360,0,360,0,0

  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_DOORBELL_USER}:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@{FRIGATE_CAMERA_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
            - rtmp
        - path: rtsp://{FRIGATE_CAMERA_DOORBELL_USER}:{FRIGATE_CAMERA_DOORBELL_PASSWORD}@{FRIGATE_CAMERA_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
    detect:
      width: 720
      height: 576
      fps: 15
    record:
      enabled: True
      retain_days: 14
      events:
        objects:
          - person
        retain:
          # Required: Default retention days (default: shown below)
          default: 14
    snapshots:
      enabled: True
      timestamp: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
    rtmp:
      enabled: True
    objects:
      track:
        - person
