# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: bookstack-helm-values
#   namespace: default
# spec:
#   encryptedData:
#     values.yaml: AgCmREsLZXqEysmktWMyt/qLVpZ0GsHGEkFzmFCvW7NU2lHfvrjfmGeI25rOSi7F4HxuqM1OhkWjjPxVFZQwa8HbIZ9RVyhAayFJejqeUORAedUMEZrHdEQ+pARoIdv5A1Y9IYbX0XMEXQFlC2VEKIulk2a9CxTb9EbXbzhRoxBuYz7ZD4VtPS6E5QctUvkE5deJ1YbzfN/MfyvDNiC49esct9qRYMPZEEyvdKiC0PXOyylquRK9aICdiTU3xSelZo6Rb5KbcCASKH1/xXBavji45NiKfg1mls6fU8cC+/ynLVfGM8l8hWXWOcE6Nkpp3Jlbiqg2fWe+3kFnUtefUW2gFSJhED8Env6AHY9w7fDl42XrjZBdF8+4mPdw/3wtq8XmLxjlFzwUfQ58WOnUAkP7NR7m6Mu8MfhXQkvD3xNkuOXu3LymOPKQZ8mQWKVfZ9tJmQOaxEL5LpvH9c69zWwtBPqVsBiaQwAwFxkEnHEyppv/veWxU3zeEwDXdFL92hZKLYfjJ9m8rUA1pPttkCqxcFln0bvwAxFAc80Jjq8OCjRv/v6qnZa6d+626j5g4Hb86S4WJxH176Bo5yX9gQ2T8b4rZFMLbmIHxtlnJQcbEENNk+3n8tSXBnZvbL7Nu8qgyWYa71siUpaRXVt1C8jvxw126DcpmucB+hrWCQ2dktYJ2B5+yGA6AOssy7lXBClRUGJ5yV2cTumDH0I3BVx70cYmY6266QEhdUidpurAvjhBfbH2vdVfbJZCHuN+7e5Q12E4AYwBeYnDrYZUIE+XMeVwBy7HSgcdKrXBeKFi+BzfKmvEEw+h6yA7QtY6k3Oct2JavzATc1AYMPB8Js9292clcUTF+nM9Hfw4JZPIIPdOb5SxTfTCNWMys6z4sJYkZmcXQbUfHJ6NXTjh2OEhAcBl+Nrfjy7Gns4=
#   template:
#     metadata:
#       creationTimestamp: null
#       name: bookstack-helm-values
#       namespace: default
