---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: yourls
  namespace: collab
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.yourls.org/
      chart: yourls
      version: 5.2.2
      sourceRef:
        kind: HelmRepository
        name: yourls-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: yourls
      tag: 1.8.2-fpm-alpine

    yourls:
      site: ${SECRET_SHORT_DOMAIN}
      username: ryan
      password: ${SECRET_YOURLS_ADMIN_PASSWORD}

    db:
      host: yourls-mysql
      port: 3306
      user: yourls
      password: ${SECRET_YOURLS_MYSQL_PASSWORD}
      database: yourls

    service:
      type: ClusterIP
      externalTrafficPolicy: Local

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - name: ${SECRET_SHORT_DOMAIN}
          path: /
          tls: true
          tlsSecret: tls-yourls

    persistence:
      enabled: true
      existingClaim: yourls-config-pvc

    metrics:
      enabled: true

    mysql:
      auth:
        rootPassword: ${SECRET_YOURLS_MYSQL_ROOT_PASSWORD}
        password: ${SECRET_YOURLS_MYSQL_PASSWORD}
      primary:
        persistence:
          existingClaim: yourls-mysql-pvc
